apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - name: "validating-deployment.image-cloner.io"
    namespaceSelector:
      matchExpressions:
        - key: validate-backups.image-cloner.io
          operator: NotIn
          values: ["disable"]
    rules:
      - apiGroups:   ["*"]
        apiVersions: ["*"]
        operations:  ["UPDATE"]
        resources:   ["deployments"]
        scope:       "Namespaced"
    clientConfig:
      service:
        namespace: default
        name: image-cloner
        path: /validate-deployment
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR4RENDQXF5Z0F3SUJBZ0lVRlBzR0VvaU9FaDBHbS9iWWVJNmh3UG1PL25Zd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2FERUxNQWtHQTFVRUJoTUNWVk14RHpBTkJnTlZCQWdUQms5eVpXZHZiakVSTUE4R0ExVUVCeE1JVUc5eQpkR3hoYm1ReEV6QVJCZ05WQkFvVENrdDFZbVZ5Ym1WMFpYTXhDekFKQmdOVkJBc1RBa05CTVJNd0VRWURWUVFECkV3cExkV0psY201bGRHVnpNQjRYRFRJeE1ERXpNREUwTURnd01Gb1hEVEkyTURFeU9URTBNRGd3TUZvd2FERUwKTUFrR0ExVUVCaE1DVlZNeER6QU5CZ05WQkFnVEJrOXlaV2R2YmpFUk1BOEdBMVVFQnhNSVVHOXlkR3hoYm1ReApFekFSQmdOVkJBb1RDa3QxWW1WeWJtVjBaWE14Q3pBSkJnTlZCQXNUQWtOQk1STXdFUVlEVlFRREV3cExkV0psCmNtNWxkR1Z6TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF3VXhqMHNjVkNuYTIKUGkxVHhBa0M5Z1dscFZlTThZS2xGU2dsK1Bjb0ZJRWtPbE5FdkxScVZnYVFQdTlkUE9CWU1OY2xBY1ZJbVJWNApyRjVWdVZXMzk4Y3NoRHJGN2MxLytNUmpUVjc4bVhObXh0MVBrWEpWREcwNk0rc0E3QXdMK1RBZzN0VUNOdVJrClpuT2cxU1ZoYkFzTmdEL0lKU2dhYk5vYXkzTkZlTWhtS0ZPUW9tOEtBOTIyRThZK2Q0a1BGNm9SYjBVbEN4Y2MKdzRRZnVwbjV3UTAzMXk1ZjhkZnl6b1FCWmZJVDVja3lzRmtic3hMZXRhU2ptWVkxMUZFZnhSd3lXeWRqeEZ5VQpOQkV0aTFFOCt0cFZjN1luMTBONmlzZk9UYzRLVDZMRVdyOE1Dek5uVGdNMTZ2R2x5R0prb3FqTGRnUytGMkpMCnR1TXk0bm1MQXdJREFRQUJvMll3WkRBT0JnTlZIUThCQWY4RUJBTUNBUVl3RWdZRFZSMFRBUUgvQkFnd0JnRUIKL3dJQkFqQWRCZ05WSFE0RUZnUVU2Ui9nQVYxdW1KQ1gxeko2NXowam5ZZmJ2WjB3SHdZRFZSMGpCQmd3Rm9BVQo2Ui9nQVYxdW1KQ1gxeko2NXowam5ZZmJ2WjB3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUVNaGc5VDVEY3JnCkw2MTRTajBCUldETnNVMFhoQUErRlQ1THpIajE1eWU2MytSWnlDSHc0eW00RFYvYVdWc1VkVVpuelJDZzFoNjkKR3RRWnVnc1VCRi83aDh0UWNpOGtrdWkzeWZXYjlSbEdNNnQxQ1J5R2x4YlZ3dDBpckZiNWdibVMyeFZNTjhVSApSN1JCa2tpUFMwRVVUaXp2REV4dVBncUl6b0FvdnVHM2NtMVBEMzZOdEtIUERCd1VMbDg1SmErTUhleFBCTlVOCjZKM3BKWGlBb1RONmJGL2dFMU9nYkZiYzZPbXRuRGVEQmFtUm52N3pBNXNmQ0hCYU8wSU9JRW9LODl3YTNjY2gKZGxTbFlVUzM3WGI1OWdpTi9wa1o1dnFJL0FZSmZVV1FpNERCZ1RsRlNCR3BPaW9CaWRlWkVBdiswc0JqTnpiYwpFYVlPZmxrN2N1ST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    admissionReviewVersions: ["v1"]
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-daemonset
webhooks:
  - name: "validating-daemonset.image-cloner.io"
    namespaceSelector:
      matchExpressions:
        - key: validate-backups.image-cloner.io
          operator: NotIn
          values: ["disable"]
    rules:
      - apiGroups:   ["*"]
        apiVersions: ["*"]
        operations:  ["UPDATE"]
        resources:   ["daemonset"]
        scope:       "Namespaced"
    clientConfig:
      service:
        namespace: default
        name: image-cloner
        path: /validate-deployment
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR4RENDQXF5Z0F3SUJBZ0lVRlBzR0VvaU9FaDBHbS9iWWVJNmh3UG1PL25Zd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2FERUxNQWtHQTFVRUJoTUNWVk14RHpBTkJnTlZCQWdUQms5eVpXZHZiakVSTUE4R0ExVUVCeE1JVUc5eQpkR3hoYm1ReEV6QVJCZ05WQkFvVENrdDFZbVZ5Ym1WMFpYTXhDekFKQmdOVkJBc1RBa05CTVJNd0VRWURWUVFECkV3cExkV0psY201bGRHVnpNQjRYRFRJeE1ERXpNREUwTURnd01Gb1hEVEkyTURFeU9URTBNRGd3TUZvd2FERUwKTUFrR0ExVUVCaE1DVlZNeER6QU5CZ05WQkFnVEJrOXlaV2R2YmpFUk1BOEdBMVVFQnhNSVVHOXlkR3hoYm1ReApFekFSQmdOVkJBb1RDa3QxWW1WeWJtVjBaWE14Q3pBSkJnTlZCQXNUQWtOQk1STXdFUVlEVlFRREV3cExkV0psCmNtNWxkR1Z6TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF3VXhqMHNjVkNuYTIKUGkxVHhBa0M5Z1dscFZlTThZS2xGU2dsK1Bjb0ZJRWtPbE5FdkxScVZnYVFQdTlkUE9CWU1OY2xBY1ZJbVJWNApyRjVWdVZXMzk4Y3NoRHJGN2MxLytNUmpUVjc4bVhObXh0MVBrWEpWREcwNk0rc0E3QXdMK1RBZzN0VUNOdVJrClpuT2cxU1ZoYkFzTmdEL0lKU2dhYk5vYXkzTkZlTWhtS0ZPUW9tOEtBOTIyRThZK2Q0a1BGNm9SYjBVbEN4Y2MKdzRRZnVwbjV3UTAzMXk1ZjhkZnl6b1FCWmZJVDVja3lzRmtic3hMZXRhU2ptWVkxMUZFZnhSd3lXeWRqeEZ5VQpOQkV0aTFFOCt0cFZjN1luMTBONmlzZk9UYzRLVDZMRVdyOE1Dek5uVGdNMTZ2R2x5R0prb3FqTGRnUytGMkpMCnR1TXk0bm1MQXdJREFRQUJvMll3WkRBT0JnTlZIUThCQWY4RUJBTUNBUVl3RWdZRFZSMFRBUUgvQkFnd0JnRUIKL3dJQkFqQWRCZ05WSFE0RUZnUVU2Ui9nQVYxdW1KQ1gxeko2NXowam5ZZmJ2WjB3SHdZRFZSMGpCQmd3Rm9BVQo2Ui9nQVYxdW1KQ1gxeko2NXowam5ZZmJ2WjB3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUVNaGc5VDVEY3JnCkw2MTRTajBCUldETnNVMFhoQUErRlQ1THpIajE1eWU2MytSWnlDSHc0eW00RFYvYVdWc1VkVVpuelJDZzFoNjkKR3RRWnVnc1VCRi83aDh0UWNpOGtrdWkzeWZXYjlSbEdNNnQxQ1J5R2x4YlZ3dDBpckZiNWdibVMyeFZNTjhVSApSN1JCa2tpUFMwRVVUaXp2REV4dVBncUl6b0FvdnVHM2NtMVBEMzZOdEtIUERCd1VMbDg1SmErTUhleFBCTlVOCjZKM3BKWGlBb1RONmJGL2dFMU9nYkZiYzZPbXRuRGVEQmFtUm52N3pBNXNmQ0hCYU8wSU9JRW9LODl3YTNjY2gKZGxTbFlVUzM3WGI1OWdpTi9wa1o1dnFJL0FZSmZVV1FpNERCZ1RsRlNCR3BPaW9CaWRlWkVBdiswc0JqTnpiYwpFYVlPZmxrN2N1ST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    admissionReviewVersions: ["v1"]
    sideEffects: None
