
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-internal
  namespace: default
  labels:
    app: traefik-internal
    type: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-internal
  template:
    metadata:
      labels:
        app: traefik-internal
        type: default
    spec:
      serviceAccountName: traefik-internal
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik:1.7.24
        name: traefik-internal
        ports:
        - name: http
          containerPort: 80
        - name: admin
          containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100M
          requests:
            cpu: 100m
            memory: 100M
        args:
        - --api
        - --kubernetes
        - --logLevel=INFO
        - --kubernetes.ingressClass=traefik-internal
        - --kubernetes.ingressEndpoint.publishedService=default/traefik-internal
        - --metrics.prometheus

