apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: containous/whoami:v1.4.0 
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 50m
            memory: 30M
          requests:
            cpu: 30m
            memory: 20M 
  
